### ISSUE TITLE
Play icon missing

### ISSUE THREAD

**Issue by FriendsNone** [vicr123/themedia#1]
It's self explanatory, no need to explain furter.

**Comment by vicr123** [comment]
@FriendsNone This should actually be filed under theShell because that's a theShell problem. Could you do that please? :)

...unless of course you mean the play button on the theMedia UI in which case just tell me and I'll reopen this :)

**Comment by FriendsNone** [comment]
If you want to then I'm fine with it. Should I still post on theShell?

**Comment by vicr123** [comment]
Yeah because that's a theShell issue :)
